### ISSUE TITLE
Update Nutri-Score page based on Santé publique France feedback

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-web#377]
### What

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
- [ ] Update Nutri-Score page based on Santé publique France feedback
- [ ] Update the page in general
- [ ] Replace old videos
- [ ] Remove finished petition
```

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-web/pull/345
