### ISSUE TITLE
Press page (refactoring)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-web#550]
### What

```[tasklist]
### Tasks
- [ ] #549 
- [ ] #548 
- [ ] Make the color backgrounds edge to edge
- [ ] Buttons at the bottom for press releases
- [ ] Middle vertical align for the text "Our historical list of press…"
- [ ] Padding for the tooltip: "Note: this press"
- [ ] Slight radius for the tooltip: "Note: this press"
- [ ] Fix the grey background for the Media Kit
- [ ] Add a miniature of the cover of the Media Kit
- [ ] Turn each logo variant section into an accordion
- [ ] Deploy the fixed Eco-Scores: https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-b.svg
- [ ] Add the raster links for the Eco-Score https://world.openfoodfacts.org/images/eco-score-logos/ecoscore-d.png
- [ ] Commit raster version of the Eco-Score if needed
- [ ] Fix the Download as vectorial icon for Eco-Score B
- [ ] Fix the little lines appearing after Eco-Score buttons
- [ ] Add padding around the text of UN SDG goals
- [ ] Fix the link color of contact in Goal 17
- [ ] Refactor the Nutri-Score section into cards like the Eco-Score, with download buttons
- [ ] Add a 1px solid line around the email field in the subscription form for journalists
- [ ] Reformat the subscription form to feel native
- [ ] Ensure the subscription form still works
- [ ] Add a title to the mailto: link in the Press contact section: "Media enquiry". Investigate the possibility of a form and/or prefilling the email
- [ ] Fix the Screenshots of the Open Food Facts mobile app section (merge it with app visuals below?)
- [ ] Fix the Eco-Score resources section
- [ ] Document the additional podcasts we recorded
```
